<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="sailakshmi" failures="1" tests="1" name="Default test(failed)(failed)" time="0.044" errors="0" timestamp="2023-09-27T13:03:41 IST">
  <testcase classname="com.Example.TestNG.NewTest" name="subtractTest" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [3] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [-1]
at com.Example.TestNG.NewTest.subtractTest(NewTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- subtractTest -->
  <testcase classname="com.Example.TestNG.NewTest" name="addTest" time="0.0">
    <ignored/>
  </testcase> <!-- addTest -->
</testsuite> <!-- Default test(failed)(failed) -->
